apiVersion: v1
kind: Namespace
metadata:
  name: kuberpack-build
  labels:
    {{- include "kuberpack.labels" . | nindent 4 }}
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
