apiVersion: v1
kind: ResourceQuota
metadata:
  name: kuberpack-build
  namespace: kuberpack-build
spec:
  hard:
    pods: "4"
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "8"
    limits.memory: 12Gi
