apiVersion: v1
kind: Service
metadata:
  name: kuberpack
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: kuberpack
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuberpack
  namespace: {{ .Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kuberpack
                port:
                  name: http
  tls:
    - hosts:
        - {{ .Values.host | quote }}
