package promote

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// ensureSecretCR writes an InfisicalStaticSecret for the app's declared
// Infisical keys and makes sure the parent kustomization lists it. Returns the
// paths touched and whether anything changed. No-op when the platform has no
// Infisical project or the app declares no secrets.
func ensureSecretCR(work string, spec AppSpec, p Platform) ([]string, bool, error) {
	p = p.withDefaults()
	if !p.InfisicalEnabled() || len(spec.Secrets) == 0 {
		return nil, false, nil
	}
	crRel := p.InfisicalCRPath(spec.Name)
	parentRel := p.InfisicalParentPath()
	crPath := filepath.Join(work, filepath.FromSlash(crRel))
	if err := os.MkdirAll(filepath.Dir(crPath), 0o755); err != nil {
		return nil, false, err
	}
	if err := os.WriteFile(crPath, []byte(infisicalCRContent(spec, p)), 0o644); err != nil {
		return nil, false, err
	}

	parentPath := filepath.Join(work, filepath.FromSlash(parentRel))
	raw, err := os.ReadFile(parentPath)
	if os.IsNotExist(err) {
		raw = []byte("apiVersion: kustomize.config.k8s.io/v1beta1\nkind: Kustomization\nresources:\n")
	} else if err != nil {
		return nil, false, err
	}
	resource := strings.TrimSuffix(filepath.Base(crRel), ".yaml")
	if !listedInKustomization(raw, resource) {
		if err := os.WriteFile(parentPath, appendKustomizationResource(raw, resource), 0o644); err != nil {
			return nil, false, err
		}
	}
	return []string{crRel, parentRel}, true, nil
}

// removeSecretCR deletes the app's InfisicalStaticSecret and its parent entry.
// No-op when the platform has no Infisical project.
func removeSecretCR(work string, spec AppSpec, p Platform) ([]string, bool, error) {
	p = p.withDefaults()
	if !p.InfisicalEnabled() {
		return nil, false, nil
	}
	crRel := p.InfisicalCRPath(spec.Name)
	parentRel := p.InfisicalParentPath()
	crPath := filepath.Join(work, filepath.FromSlash(crRel))
	_, statErr := os.Stat(crPath)
	if statErr != nil && !os.IsNotExist(statErr) {
		return nil, false, statErr
	}
	if err := os.Remove(crPath); err != nil && !os.IsNotExist(err) {
		return nil, false, err
	}

	parentPath := filepath.Join(work, filepath.FromSlash(parentRel))
	if raw, err := os.ReadFile(parentPath); err == nil {
		resource := strings.TrimSuffix(filepath.Base(crRel), ".yaml")
		if listedInKustomization(raw, resource) {
			if err := os.WriteFile(parentPath, removeKustomizationResource(raw, resource), 0o644); err != nil {
				return nil, false, err
			}
		}
	}
	return []string{crRel, parentRel}, true, nil
}

func infisicalCRContent(spec AppSpec, p Platform) string {
	p = p.withDefaults()
	var b strings.Builder
	b.WriteString("# Generated by Kuberpack. The values stay in Infisical; this object only references keys.\n")
	b.WriteString("apiVersion: secrets.infisical.com/v1beta1\n")
	b.WriteString("kind: InfisicalStaticSecret\n")
	b.WriteString("metadata:\n")
	b.WriteString("  name: " + AppRuntimeSecretName(spec.Name) + "\n")
	b.WriteString("  namespace: " + p.InfisicalNamespace + "\n")
	b.WriteString("spec:\n")
	b.WriteString("  infisicalAuthRef:\n")
	b.WriteString("    name: " + p.InfisicalAuthRef + "\n")
	b.WriteString("    namespace: " + p.InfisicalNamespace + "\n")
	b.WriteString("  sources:\n")
	b.WriteString("    - projectId: " + p.InfisicalProjectID + "\n")
	b.WriteString("      environmentSlug: " + secretEnv(spec) + "\n")
	b.WriteString("      secretPath: " + p.InfisicalPath + "\n")
	b.WriteString("  syncOptions:\n")
	b.WriteString("    refreshInterval: 1m\n")
	b.WriteString("  targets:\n")
	b.WriteString("    - kind: Secret\n")
	b.WriteString("      name: " + AppRuntimeSecretName(spec.Name) + "\n")
	b.WriteString("      namespace: " + p.ReleaseNamespace + "\n")
	b.WriteString("      creationPolicy: Orphan\n")
	b.WriteString("      template:\n")
	b.WriteString("        engineVersion: v1\n")
	b.WriteString("        data:\n")
	for _, key := range spec.Secrets {
		b.WriteString(fmt.Sprintf("          %s: '{{ (index . %q).Value }}'\n", key, key))
	}
	return b.String()
}

func secretEnv(spec AppSpec) string {
	if env := strings.TrimSpace(spec.SecretEnv); env != "" {
		return env
	}
	return "prod"
}

// normalizeSecretKeys trims, drops empties and de-duplicates while keeping order.
func normalizeSecretKeys(keys []string) []string {
	seen := map[string]bool{}
	out := make([]string, 0, len(keys))
	for _, k := range keys {
		k = strings.TrimSpace(k)
		if k == "" || seen[k] {
			continue
		}
		seen[k] = true
		out = append(out, k)
	}
	return out
}

// NormalizeSecretKeys trims, drops empties and de-duplicates while keeping order.
func NormalizeSecretKeys(keys []string) []string {
	return normalizeSecretKeys(keys)
}
