package promote

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// PreviewDatabaseName is the CloudNativePG Cluster dedicated to a preview
// release (app-<app>-pr-<n>-db). It is empty by design: the app creates the
// schema with its own migrations, and production data never reaches it.
func PreviewDatabaseName(releaseName string) string {
	return sanitizeName(releaseName) + "-db"
}

func (p Platform) PreviewDatabasePath(releaseName string) string {
	return filepath.ToSlash(filepath.Join(p.withDefaults().AppDir(releaseName), "database.yaml"))
}

// ensurePreviewDatabase writes an empty CloudNativePG Cluster for the preview
// and makes sure the app kustomization lists it. No-op unless enabled.
func ensurePreviewDatabase(work string, spec AppSpec, p Platform) (bool, error) {
	p = p.withDefaults()
	if !spec.Preview || !spec.PreviewDatabase {
		return false, nil
	}
	dir := filepath.Join(work, filepath.FromSlash(p.AppDir(spec.Name)))
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return false, err
	}
	rel := p.PreviewDatabasePath(spec.Name)
	path := filepath.Join(work, filepath.FromSlash(rel))
	changed := false
	if _, err := os.Stat(path); os.IsNotExist(err) {
		if err := os.WriteFile(path, []byte(previewDatabaseYAML(spec, p)), 0o644); err != nil {
			return false, err
		}
		changed = true
	} else if err != nil {
		return false, err
	}

	// Add database.yaml to the app kustomization's resources.
	kPath := filepath.Join(work, filepath.FromSlash(p.AppDir(spec.Name)), "kustomization.yaml")
	raw, err := os.ReadFile(kPath)
	if err != nil {
		return false, err
	}
	if !listedInKustomization(raw, "database.yaml") {
		if err := os.WriteFile(kPath, appendKustomizationResource(raw, "database.yaml"), 0o644); err != nil {
			return false, err
		}
		changed = true
	}
	return changed, nil
}

// previewDatabaseYAML renders an empty, single-instance CNPG cluster. CNPG
// generates the <name>-app Secret (username/password/host/uri) on its own, so
// no credential is ever written to Git.
func previewDatabaseYAML(spec AppSpec, p Platform) string {
	p = p.withDefaults()
	name := PreviewDatabaseName(spec.Name)
	var b strings.Builder
	b.WriteString("# Generated by Kuberpack. Empty preview database; the app creates its\n")
	b.WriteString("# schema with its own migrations. Never a copy of production data.\n")
	b.WriteString("apiVersion: postgresql.cnpg.io/v1\n")
	b.WriteString("kind: Cluster\n")
	b.WriteString("metadata:\n")
	b.WriteString("  name: " + name + "\n")
	b.WriteString("  namespace: " + p.ReleaseNamespace + "\n")
	b.WriteString("  labels:\n")
	b.WriteString("    kuberpack.io/addon: postgres\n")
	b.WriteString("    kuberpack.io/for: " + sanitizeName(spec.Name) + "\n")
	b.WriteString("spec:\n")
	b.WriteString("  instances: 1\n")
	b.WriteString("  imageName: " + p.PreviewDatabaseImage + "\n")
	b.WriteString("  imagePullPolicy: IfNotPresent\n")
	b.WriteString("  inheritedMetadata:\n")
	b.WriteString("    labels:\n")
	b.WriteString("      kuberpack.io/addon: postgres\n")
	b.WriteString("      kuberpack.io/for: " + sanitizeName(spec.Name) + "\n")
	b.WriteString("  primaryUpdateStrategy: unsupervised\n")
	b.WriteString("  enableSuperuserAccess: false\n")
	b.WriteString("  bootstrap:\n")
	b.WriteString("    initdb:\n")
	b.WriteString("      database: app\n")
	b.WriteString("      owner: app\n")
	b.WriteString("      encoding: UTF8\n")
	b.WriteString("      dataChecksums: true\n")
	b.WriteString("  storage:\n")
	b.WriteString("    storageClass: " + p.PreviewDatabaseClass + "\n")
	b.WriteString("    size: " + p.PreviewDatabaseStorage + "\n")
	b.WriteString("  resources:\n")
	b.WriteString("    requests: { cpu: 50m, memory: 128Mi }\n")
	b.WriteString("    limits: { cpu: 500m, memory: 512Mi }\n")
	b.WriteString("  monitoring:\n")
	b.WriteString("    enablePodMonitor: false\n")
	return b.String()
}

// previewDatabaseEnvYAML returns the literal env entries that expose the
// preview database to the app, pulling the value from the CNPG-generated
// Secret (so nothing secret is in Git).
func previewDatabaseEnvYAML(spec AppSpec) string {
	name := PreviewDatabaseName(spec.Name)
	return fmt.Sprintf("- name: DATABASE_URL\n  valueFrom:\n    secretKeyRef:\n      name: %s-app\n      key: uri\n      optional: true\n", name)
}
